language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.1.3
  - 2.2.0
  - ruby-head

env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.9"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
